# https://yunohost.org/en/packaging_config_panels
# https://github.com/YunoHost/example_ynh/blob/master/config_panel.toml.example

version = "1.0"

[main]
name.en = "Main configuration"
name.fr = "Configuration principale"
services = ["__APP__"]

    [main.config]
    name = "Configuration Options"

        [main.config.default_from_email]
        ask = "from email"
        type = "email"
        help = "Default email address to use for various automated emails."
        #
        # We can't use "__DATA_DIR__" in bind value, because of this bug:
        # https://github.com/YunoHost/issues/issues/2283
        bind = "default_from_email:/home/yunohost.app/__APP__/settings.py"

        [main.config.admin_email]
        ask = "ADMIN email"
        type = "email"
        help = "EMail address for error emails."
        bind = "admin_email:/home/yunohost.app/__APP__/settings.py"

        [main.config.debug_enabled]
        ask = "DEBUG mode"
        type = "boolean"
        yes = "1"
        no = "0"
        help = "Enable DEBUG mode? (Should be never enabled in production!)"
        bind = "debug_enabled:/home/yunohost.app/__APP__/settings.py"

        [main.config.log_level]
        type = "string"
        ask = "Log Level"
        choices = ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]
        default = "WARNING"
        bind = "log_level:/home/yunohost.app/__APP__/settings.py"

        [main.config.realtime_enabled]
        ask = "Realtime"
        type = "boolean"
        yes = "1"
        no = "0"
        help = "Allow for realtime collaboration"
        bind = "realtime_enabled:/home/yunohost.app/__APP__/settings.py"

        [main.config.allow_anonymous]
        ask = "Anonymous edition"
        type = "boolean"
        yes = "1"
        no = "0"
        help = "Allow for non logged in users to create and edit maps"
        bind = "allow_anonymous:/home/yunohost.app/__APP__/settings.py"

        [main.config.default_longitude]
        ask = "Default longitude"
        type = "string"
        default = "2.0"
        help = "Default longitude for new maps"
        bind = "default_longitude:/home/yunohost.app/__APP__/settings.py"

        [main.config.default_latitude]
        ask = "Default latitude"
        type = "string"
        default = "51.0"
        help = "Default latitude for new maps"
        bind = "default_latitude:/home/yunohost.app/__APP__/settings.py"

        [main.config.default_zoom]
        ask = "Default zoom"
        type = "number"
        default = "6"
        help = "Default zoom for new maps"
        bind = "default_zoom:/home/yunohost.app/__APP__/settings.py"

        [main.config.openrouteservice]
        ask = "OpenRouteService"
        type = "string"
        default = ""
        help = "Add your OpenRouteService APi key to activate the routing. The key can be created here: https://openrouteservice.org/"
        bind = "openrouteservice:/home/yunohost.app/__APP__/settings.py"
